linters:
  eslint:
    config: './eslint.config'
files:
  ignore:
      - 'dist/*'
      - '.eslintrc.js'
      - '/src/component/*'
      - '/src/index.js'

































































































        